const mainCryptoTypes = {
  GET_ALL_CRYPTOCURRENCY: 'GET_ALL_CRYPTOCURRENCY',
  FIND_CRYPTOCURRENCY: 'FIND_CRYPTOCURRENCY',
  SORT_DESCENDING_PRICE: 'SORT_DESCENDING_PRICE',
  SORT_ASCENDING_PRICE: 'SORT_ASCENDING_PRICE',
};
export default mainCryptoTypes;
