const mainCryptoTypes = {
  GET_ALL_CRYPTOCURRENCY_START: 'GET_ALL_CRYPTOCURRENCY_START',
  GET_ALL_CRYPTOCURRENCY_SUCCESS: 'GET_ALL_CRYPTOCURRENCY_SUCCESS',
  GET_ALL_CRYPTOCURRENCY_ERROR: 'GET_ALL_CRYPTOCURRENCY_ERROR',
  FIND_CRYPTOCURRENCY: 'FIND_CRYPTOCURRENCY',
  SORT_DESCENDING_PRICE: 'SORT_DESCENDING_PRICE',
  SORT_ASCENDING_PRICE: 'SORT_ASCENDING_PRICE',
};
export default mainCryptoTypes;
